channels:
  - conda-forge
name: py35
dependencies:
- openssl
- pip
- python=3.5.3
- readline
- setuptools
- sqlite
- wheel
- zlib
- pip:
  - Sphinx
  - pylint
  - pytest
  - pytest-cov
  - sphinx-autodoc-typehints
  - setuptools_scm
